# Docker Compose file for local development environment
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      - TZ=UTC
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Altinors123!
      POSTGRES_USER: memory_mcp_user
      POSTGRES_DB: memory_mcp_db
      TZ: UTC
    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  qdrant_storage:
  postgres_data:
  rabbitmq_data:
  redis_data: 