"""add server_properties table

Revision ID: 7863b196ef92
Revises: de7cfeb9cd83
Create Date: 2025-06-11 22:03:52.037923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7863b196ef92'
down_revision: Union[str, None] = 'de7cfeb9cd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_properties_id'), 'server_properties', ['id'], unique=False)
    op.create_index(op.f('ix_server_properties_name'), 'server_properties', ['name'], unique=True)
    # ### end Alembic commands ###

    # Insert default is_registration_active property
    op.execute("""
        INSERT INTO server_properties (name, value, description, active, arguments)
        VALUES ('is_registration_active', 'true', 'Controls whether new user registrations are allowed', true, '{}')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_properties_name'), table_name='server_properties')
    op.drop_index(op.f('ix_server_properties_id'), table_name='server_properties')
    op.drop_table('server_properties')
    # ### end Alembic commands ###
