"""Add default user and fix metadata_json column

Revision ID: b82f803be60c
Revises: 215f76b3a0fc
Create Date: 2025-06-04 15:49:44.530672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82f803be60c'
down_revision: Union[str, None] = '215f76b3a0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename profile_data column to metadata_json in processed_user_profiles table
    op.alter_column('processed_user_profiles', 'profile_data', new_column_name='metadata_json')
    
    # Insert default/placeholder user
    from sqlalchemy import text
    op.execute(text("""
        INSERT INTO users (id, email, username, hashed_password, is_active, is_superuser) 
        VALUES ('00000000-0000-0000-0000-000000000000', 'placeholder@system.local', 'placeholder_user', 'placeholder_hash', true, false)
        ON CONFLICT (id) DO NOTHING;
    """))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove the placeholder user
    from sqlalchemy import text
    op.execute(text("DELETE FROM users WHERE id = '00000000-0000-0000-0000-000000000000';"))
    
    # Rename metadata_json column back to profile_data
    op.alter_column('processed_user_profiles', 'metadata_json', new_column_name='profile_data')
    
    # ### end Alembic commands ###
