"""Add API key fields to User model

Revision ID: de7cfeb9cd83
Revises: b82f803be60c
Create Date: 2025-06-04 17:04:24.208494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7cfeb9cd83'
down_revision: Union[str, None] = 'b82f803be60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_column('users', 'api_key_created_at')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
